---
development:
  cloud_name: shroomcrumpet
  api_key: '371364174336437'
  api_secret: tJDlCfkGz4sZeJhzZJYAqembIxA
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: shroomcrumpet
  api_key: '371364174336437'
  api_secret: tJDlCfkGz4sZeJhzZJYAqembIxA
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: shroomcrumpet
  api_key: '371364174336437'
  api_secret: tJDlCfkGz4sZeJhzZJYAqembIxA
  enhance_image_tag: true
  static_image_support: false
